/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package pipeline.model.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class KafkaEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KafkaEvent\",\"namespace\":\"pipeline.model.avro\",\"fields\":[{\"name\":\"data\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.Map<java.lang.String,java.lang.String> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public KafkaEvent() {}

  /**
   * All-args constructor.
   */
  public KafkaEvent(java.util.Map<java.lang.String,java.lang.String> data) {
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.Map<java.lang.String,java.lang.String> value) {
    this.data = value;
  }

  /** Creates a new KafkaEvent RecordBuilder */
  public static pipeline.model.avro.KafkaEvent.Builder newBuilder() {
    return new pipeline.model.avro.KafkaEvent.Builder();
  }
  
  /** Creates a new KafkaEvent RecordBuilder by copying an existing Builder */
  public static pipeline.model.avro.KafkaEvent.Builder newBuilder(pipeline.model.avro.KafkaEvent.Builder other) {
    return new pipeline.model.avro.KafkaEvent.Builder(other);
  }
  
  /** Creates a new KafkaEvent RecordBuilder by copying an existing KafkaEvent instance */
  public static pipeline.model.avro.KafkaEvent.Builder newBuilder(pipeline.model.avro.KafkaEvent other) {
    return new pipeline.model.avro.KafkaEvent.Builder(other);
  }
  
  /**
   * RecordBuilder for KafkaEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KafkaEvent>
    implements org.apache.avro.data.RecordBuilder<KafkaEvent> {

    private java.util.Map<java.lang.String,java.lang.String> data;

    /** Creates a new Builder */
    private Builder() {
      super(pipeline.model.avro.KafkaEvent.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(pipeline.model.avro.KafkaEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing KafkaEvent instance */
    private Builder(pipeline.model.avro.KafkaEvent other) {
            super(pipeline.model.avro.KafkaEvent.SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'data' field */
    public java.util.Map<java.lang.String,java.lang.String> getData() {
      return data;
    }
    
    /** Sets the value of the 'data' field */
    public pipeline.model.avro.KafkaEvent.Builder setData(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'data' field has been set */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'data' field */
    public pipeline.model.avro.KafkaEvent.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public KafkaEvent build() {
      try {
        KafkaEvent record = new KafkaEvent();
        record.data = fieldSetFlags()[0] ? this.data : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
